journey/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

app_name = 'journey'

urlpatterns = [
                  path('', views.post_list, name='post_list'),
                  path('post_list', views.post_list, name='post_list'),
                  path('signup', views.signup, name='signup'),
                  path('post_detail', views.post_detail, name='post_detail'),
                  path('post/create/', views.post_new, name='post_new'),
                  path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
                  path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
                  path('comment_list', views.comment_list, name='comment_list'),
                  path('comment/<int:pk>/edit/', views.comment_edit, name='comment_edit'),
                  path('comment/<int:pk>/delete/', views.comment_delete, name='comment_delete'),
                  path('travelblog_post/<int:post_id>', views.travelblog_post, name='travelblog_post'),

                  path('accounts/password_reset/',
                       auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"),
                       name='password_reset'),
                  path('accounts/password_reset/done/',
                       auth_views.PasswordResetDoneView.as_view(template_name="registration/reset_email_sent.html"),
                       name='reset_email_sent'),
                  path('accounts/reset/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(template_name="registration/reset_confirm.html"),
                       name='reset_confirm'),
                  path('accounts/reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(template_name="registration/reset_complete.html"),
                       name='reset_complete'),

                  path('accounts/password_change/',
                       auth_views.PasswordChangeView.as_view(template_name="registration/password_change.html"),
                       name='password_change'),
                  path('accounts/password_change/done/',
                       auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_changed.html"),
                       name='password_changed'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

travelblog/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('journey.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

journey/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


# Create your models here
class Post(models.Model):
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='travelblog_posts')
    image_url = models.URLField()
    visited_places = models.CharField(max_length=100)
    visited_date = models.DateField('Date')
    favorite_place = models.CharField(max_length=250)
    address = models.CharField(max_length=500, blank=True, help_text='Optional')
    favorite_activity = models.CharField(max_length=250, blank=True, help_text='Optional')
    description = RichTextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = RichTextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.body}'

journey/forms.py
from django import forms
from .models import Post, Comment
from django.forms.widgets import DateInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title', 'image_url', 'visited_places', 'visited_date', 'favorite_place', 'address', 'favorite_activity',
            'description')
        # Reference - https://stackoverflow.com/questions/41224035/django-form-field-label-how-to-change-its-value-if
        # -it-belongs-to-a-certain-fi
        labels = {'visited_date': "Visited Date"}
        # Reference https://stackoverflow.com/questions/3367091/whats-the-cleanest-simplest-to-get-running-datepicker
        # -in-django
        widgets = {'visited_date': DateInput(attrs={'type': 'date', 'placeholder':'Select a date'})}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class CreateUserAccountForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, help_text='Required')
    last_name = forms.CharField(max_length=20, help_text='Required')
    email = forms.EmailField(max_length=60, help_text='Required')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')

journey/views.py
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.core.paginator import Paginator, EmptyPage, \
    PageNotAnInteger

now = timezone.now()


def post_list(request):
    object_list = Post.objects.all().order_by('-publish')
    # Pagination
    paginator = Paginator(object_list, 6)  # 6 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'journey/post_list.html',
                  {'page': page,
                   'posts': posts})


def signup(request):
    if request.method == 'POST':
        user_form = CreateUserAccountForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            username = user_form.cleaned_data.get('username')
            password = user_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("journey:post_list")
    else:
        user_form = CreateUserAccountForm()
    return render(request, 'journey/signup.html', {'user_form': user_form})


# to view details of the post from the application
@login_required
def post_detail(request):
    posts = Post.objects.all()
    return render(request, 'journey/post_detail.html',
                  {'posts': posts})


# to add new post from the application
@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.created_date = timezone.now()
            post.save()
            return redirect('journey:post_list')
    else:
        form = PostForm()
        return render(request, 'journey/post_new.html', {'form': form})


# to edit the post from the application
@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        # update
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.updated_date = timezone.now()
            post.save()
            if request.user.is_superuser:
                return redirect('journey:post_detail')
            else:
                newrequest = HttpRequest()
                newrequest.method = 'GET'
                newrequest.user = request.user
                return travelblog_post(newrequest, post.pk)
    else:
        # edit
        form = PostForm(instance=post)
    return render(request, 'journey/post_edit.html', {'form': form})


# to delete the post from the application
@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    if request.user.is_superuser:
        return redirect('journey:post_detail')
    else:
        return redirect('journey:post_list')


def travelblog_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    # List of active comments for this post
    comments = post.comments.filter()
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            new_comment.name = request.user.first_name
            new_comment.email = request.user.email
            # Save the comment to the database
            new_comment.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    return render(request, 'journey/travelblog_post.html',
                  {'post': post, 'comments': comments,
                   'comment_form': comment_form})


# comment list view from the application
@login_required
def comment_list(request):
    comments = Comment.objects.all()
    return render(request, 'journey/comment_list.html',
                  {'comments': comments})


# to edit the comment from the application
@login_required
def comment_edit(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == "POST":
        # update
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.updated_date = timezone.now()
            comment.save()
            return redirect('journey:comment_list')
    else:
        # edit
        form = CommentForm(instance=comment)
    return render(request, 'journey/comment_edit.html', {'form': form})


# to delete the comment from the application
@login_required
def comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('journey:comment_list')

templates/journey/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
<style>
    body{
        background:linear-gradient(120deg,#092E21,#ffffff);
    }
</style>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}Diary of Journey{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'journey:post_list' %}">Diary of Journey</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav col-md-10">
                <li class="nav-item"><a class="nav-link active" aria-current="page"
                                        href="{% url 'journey:post_list' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                                            href="{% url 'journey:post_new' %}">+New Post</a></li>
                {% endif %}
                {% if request.user.is_superuser %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                                            href="{% url 'journey:comment_list' %}">Comments</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                                            href="{% url 'journey:post_detail' %}">Posts</a></li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <ul class="navbar-nav me-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">{{ user.get_full_name }}</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'journey:password_change' %}">Change password</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'login' %}"><span
                            class="glyphicon glyphicon-log-in"></span>Login</a>
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                                            href="{% url 'journey:signup' %}"><span
                            class="glyphicon glyphicon-log-in"></span>Sign up</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
<!-- Header-->
<header>
    <div class="container">
        <div class="text-center">
            <h1>Diary of Journey</h1>
            <p>Share your experience to others</p>
        </div>
    </div>
</header>
<!-- Section-->
<section>
    <div class="content container">
        {% block content %}
        {% endblock %}
    </div>
</section>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>

templates/journey/comment_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'journey/base.html' %}
{% block content %}
    <h1>Edit Comment</h1>
    <form method="POST" class="comment-form">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-dark">Update</button>
    </form>
{% endblock %}
</html>

templates/journey/comment_list.html
{% extends 'journey/base.html' %}
{% block content %}
    <h1 style="padding-left: -40px; font-weight: bold; margin-top:10px">Comment Details</h1>
    <section class="py-3">
        <div>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>Post</th>
                    <th>Post Author</th>
                    <th>Commenter</th>
                    <th>Email</th>
                    <th>Body</th>
                    <th>Created Date</th>
                    <th>Updated Date</th>
                    <th colspan="3">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for comment in comments %}
                    <tr>
                        <td>{{ comment.post.title }}</td>
                        <td>{{ comment.post.author.get_full_name }}</td>
                        <td>{{ comment.name }}</td>
                        <td>{{ comment.email }}</td>
                        <td>{{ comment.body|safe }}</td>
                        <td>{{ comment.created}}</td>
                        <td>{{ comment.updated}}</td>
                        <td><a href="{% url 'journey:comment_edit' pk=comment.pk %}"
                               class="btn btn-warning">Edit</a></td>
                        <td><a href="{% url 'journey:comment_delete' pk=comment.pk %}"
                               onclick="return confirm('Are you sure you want to delete?')"
                               class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

templates/journey/comment_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'journey/base.html' %}
{% block content %}
    <h1>Add a new comment</h1>
    <form method="POST" class="comment-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-dark">Save</button>
    </form>
{% endblock %}
</html>

templates/journey/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

templates/journey/post_detail.html
{% extends 'journey/base.html' %}
{% load static %}
{% block content %}

    <h1 style="padding-left: -40px; font-weight: bold; margin-top:10px">Post Details</h1>
    <a href="{% url 'journey:post_new' %}" class="btn btn-outline-dark"
       role="button">Add Post</a>
    <section class="py-3">
        <div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Image</th>
                    <th>Visited Places</th>
                    <th>Visited Date</th>
                    <th>Favorite Place</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>Postal Code</th>
                    <th>Favorite Activity</th>
                    <th>Description</th>
                    <th>Publish</th>
                    <th colspan="3">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for post in posts %}
                    <tr>
                        <td>{{ post.title }}</td>
                        <th>{{ post.author.get_full_name }}</th>
                        <td>{{ post.image_url }}></td>
                        <td>{{ post.visited_places }}</td>
                        <td>{{ post.visited_date }}</td>
                        <td>{{ post.favorite_place }}</td>
                        <td>{{ post.address }}</td>
                        <td>{{ post.city }}</td>
                        <td>{{ post.postal_code }}</td>
                        <td>{{ post.favorite_activity }}</td>
                        <td>{{ post.description|safe }}</td>
                        <td>{{ post.publish }}</td>
                        <td><a href="{% url 'journey:post_edit' pk=post.pk %}"
                               class="btn btn-warning">Edit</a></td>
                        <td><a href="{% url 'journey:post_delete' pk=post.pk %}"
                               onclick="return confirm('Are you sure you want to delete?')"
                               class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

templates/journey/post_edit.html
<!DOCTYPE html>
{% extends 'journey/base.html' %}
<html lang="en">
{% block content %}
    <h1>Edit Post</h1>
    <form method="POST" enctype="multipart/form-data" class="post-form">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-dark">Update</button>
    </form>
{% endblock %}
</html>

templates/journey/post_list.html
{% extends "journey/base.html" %}
{% load static %}
{% block title %}Posts{% endblock %}
{% block content %}
    <style>
        img.home {
            height: 300px;
            object-fit: cover;
        }
    </style>
    {#        Reference - https://startbootstrap.com/template/shop-homepage#}
    <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-sm-1 row-cols-lg-3 row-cols-xl-3 justify-content-right">
        {% for post in posts %}
            <div class="col">
                <div>
                    <!-- Post image-->
                    <a href="{% url 'journey:travelblog_post' post_id=post.pk %}">
                        <img class="card-img home rounded" src="{{ post.image_url }}" alt="image">
                    </a>
                    <!-- Post details-->
                    <div class="card-body p-3">
                        <div class="text-left">
                            <!-- Post title-->
                            <p class="fs-4">{{ post.title }}</p>
                            <!-- Post Author-->
                            <p class="fs-5 fst-italic">{{ post.author.get_full_name }}</p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% include "journey/pagination.html" with page=posts %}
{% endblock %}

templates/journey/post_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'journey/base.html' %}
{% block content %}
    <h1>Add a new post</h1>
    <div class='form-group'>
        <form method="POST" enctype='multipart/form-data'>{% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-dark">Save</button>
        </form>
    </div>
{% endblock %}
</html>

templates/journey/signup.html
{% extends 'journey/base.html' %}
{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        <button id="btnSubmit" type="submit">Sign up</button>
    </form>
{% endblock %}

templates/journey/travelblog_post.html
{% extends "journey/base.html" %}
{% load static %}
{% block title %}Posts{% endblock %}
{% block content %}
    <style>
        img {
            height: 400px;
            object-fit: cover;
        }
    </style>
    <div class="container">
        <div>
            <h2>{{ post.title }}</h2>
            <h2>{{ post.author.get_full_name }}</h2>
        </div>
        <div class="row">
            <div class="col-md-6">
                <img src="{{ post.image_url }}" alt="image">
            </div>
            <div  class="col-md-6">
                <br>
                <p>Visited Places: {{ post.visited_places }}</p>
                <p>Visited Date: {{ post.visited_date }}</p>
                <p>Favorite Place: {{ post.favorite_place }}</p>
                <p>Address: {{ post.address }}</p>
                <p>Favorite Activity: {{ post.favorite_activity }}</p>
                {% if post.author == user %}
                    <a href="{% url 'journey:post_edit' pk=post.pk %}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'journey:post_delete' pk=post.pk %}"
                       onclick="return confirm('Are you sure you want to delete?')"
                       class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>
        <div>
            <br>
            <p class="h4">Description</p>
            <p>{{ post.description|safe }}</p>
        </div>
        {% with comments.count as total_comments %}
            <h5>
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h5>
        {% endwith %}
        {% for comment in comments %}
            <div>
                <p>
                    Comment {{ forloop.counter }} by {{ comment.name }}
                    {{ comment.created }}
                </p>
                {{ comment.body|safe }}
            </div>
        {% empty %}
            <p>There are no comments yet.</p>
        {% endfor %}
        {% if user.is_authenticated %}
            <h5>Add a new comment</h5>
            <form method="post">
                {{ comment_form.media }}
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p>
            </form>
        {% endif %}
    </div>
{% endblock %}